"""
Shared Schemas

Pydantic 모델 정의
"""

from .device import (
    DeviceBase,
    DeviceCreate,
    DeviceHeartbeat,
    DeviceInDB,
    DeviceListResponse,
    DeviceResponse,
    DeviceStatus,
    DeviceUpdate,
)
from .network import (
    APClientInfo,
    APConfig,
    APListResponse,
    APStatus,
    DHCPLease,
    DHCPPoolConfig,
    DHCPPoolListResponse,
    DHCPPoolStatus,
    DHCPStatus,
    NetworkAlertCreate,
    NetworkAlertResponse,
    NetworkHealthConfig,
    NetworkHealthResponse,
    NetworkHealthSnapshot,
    NetworkHealthSummary,
    NetworkStatus,
    VLANConfig,
    VLANDeviceDistribution,
    VLANListResponse,
    VLANStatus,
)
from .pattern import (
    HumanPatternConfig,
    InteractionPatternConfig,
    ScrollPatternConfig,
    TouchPatternConfig,
    TypingPatternConfig,
    WatchPatternConfig,
)
from .persona import (
    ATTENTION_REWARDS,
    ActivityType,
    ExistenceState,
    PersonaBase,
    PersonaCreate,
    PersonaExistence,
    PersonaInDB,
    PersonaResponse,
    PersonaTraits,
)
from .result import (
    AggregatedStats,
    ResultBase,
    ResultCreate,
    ResultInDB,
)
from .task import (
    SearchType,
    TaskBase,
    TaskCreate,
    TaskInDB,
    TaskResponse,
    TaskResultMessage,
    TaskStatus,
)
from .video import (
    VideoBase,
    VideoCreate,
    VideoInDB,
    VideoResponse,
    VideoStatus,
)
from .gateway import (
    NodeStatus as GatewayNodeStatus,
    CommandPriority,
    CommandStatus,
    TargetType,
    NodeBase,
    NodeConnection as GatewayNodeConnection,
    NodeHeartbeat,
    NodeListResponse,
    CommandTarget,
    CommandRequest,
    CommandResponse,
    QueueCommandRequest,
    QueueCommandResponse,
    BroadcastRequest,
    BroadcastResponse,
    ProtocolMessage,
    HelloMessage,
    HelloAckPayload,
    HeartbeatAckPayload,
    ResultPayload,
    ErrorPayload,
    HealthResponse,
    SystemStatusResponse,
    DashboardInitMessage,
    DashboardNodeUpdate,
    DashboardNodeConnected,
    DashboardNodeDisconnected,
    DashboardCommandResult,
)

__all__ = [
    # Device
    "DeviceStatus",
    "DeviceBase",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceInDB",
    "DeviceResponse",
    "DeviceListResponse",
    "DeviceHeartbeat",
    # Task
    "TaskStatus",
    "SearchType",
    "TaskBase",
    "TaskCreate",
    "TaskInDB",
    "TaskResponse",
    "TaskResultMessage",
    # Persona
    "ExistenceState",
    "PersonaTraits",
    "PersonaBase",
    "PersonaCreate",
    "PersonaInDB",
    "PersonaExistence",
    "PersonaResponse",
    "ActivityType",
    "ATTENTION_REWARDS",
    # Video
    "VideoStatus",
    "VideoBase",
    "VideoCreate",
    "VideoInDB",
    "VideoResponse",
    # Result
    "ResultBase",
    "ResultCreate",
    "ResultInDB",
    "AggregatedStats",
    # Pattern
    "HumanPatternConfig",
    "WatchPatternConfig",
    "TouchPatternConfig",
    "ScrollPatternConfig",
    "InteractionPatternConfig",
    "TypingPatternConfig",
    # Network (PR #3)
    "NetworkStatus",
    "APStatus",
    "DHCPStatus",
    "VLANConfig",
    "VLANStatus",
    "VLANDeviceDistribution",
    "APConfig",
    "APClientInfo",
    "DHCPPoolConfig",
    "DHCPPoolStatus",
    "DHCPLease",
    "NetworkHealthConfig",
    "NetworkHealthSummary",
    "NetworkHealthSnapshot",
    "NetworkHealthResponse",
    "VLANListResponse",
    "APListResponse",
    "DHCPPoolListResponse",
    "NetworkAlertCreate",
    "NetworkAlertResponse",
    # Gateway
    "GatewayNodeStatus",
    "CommandPriority",
    "CommandStatus",
    "TargetType",
    "NodeBase",
    "GatewayNodeConnection",
    "NodeHeartbeat",
    "NodeListResponse",
    "CommandTarget",
    "CommandRequest",
    "CommandResponse",
    "QueueCommandRequest",
    "QueueCommandResponse",
    "BroadcastRequest",
    "BroadcastResponse",
    "ProtocolMessage",
    "HelloMessage",
    "HelloAckPayload",
    "HeartbeatAckPayload",
    "ResultPayload",
    "ErrorPayload",
    "HealthResponse",
    "SystemStatusResponse",
    "DashboardInitMessage",
    "DashboardNodeUpdate",
    "DashboardNodeConnected",
    "DashboardNodeDisconnected",
    "DashboardCommandResult",
]
